### PR TITLE
[WIP] Add DNS configuration w/o dnsmasq deployed

### PR DESCRIPTION
**Pull request by bogdando**
When dnsmasq is disabled:
* re-configure the 1st nameserver for hosts via Heat stack update,
* point it to be the dns[0] host's private IP.
* ignore alternative ways to configure DNS (external_nsupdate_keys)
* drop pos-provision /etc/reslov.conf nameserver hacks as those
  expected to be persisted by cloud-init and network manager.

Fix dns floating IPs output and add the priv IPs output as well.
Update docs.
TODO add missing docs for external_nsupdate_keys, public_dns_server.
TODO persist post-provision /etc/reslov.conf nameserver hacks when using dnsmasq.

Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>

### CODE REVIEW

**Comment by bogdando** [comment]
@oybed PTAL rebased dnsmasq changes on top of your recent work

**Comment by tomassedovic** [comment]
@bogdando could you move this PR to the upstream openshift-ansible-contrib?

**Comment by bogdando** [comment]
um, sorry for confusion, but wasn't it reverted?

**Comment by tomassedovic** [comment]
Yes, but then it's been merged right back. The revert happened because the first merge squashed all the commits out of habit so we've lost the history of the CASL repo. So we reverted it and re-merged correctly.

**Comment by bogdando** [comment]
resubmitted as https://github.com/openshift/openshift-ansible-contrib/pull/471

**Pull request closed without merging**
